const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Spritefont2,
		C3.Behaviors.Sin,
		C3.Behaviors.Flash,
		C3.Plugins.Browser,
		C3.Plugins.Audio,
		C3.Plugins.gamepad,
		C3.Plugins.Keyboard,
		C3.Plugins.Sprite,
		C3.Behaviors.Tween,
		C3.Behaviors.Anchor,
		C3.Plugins.PlatformInfo,
		C3.Plugins.Particles,
		C3.Plugins.TiledBg,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.System.Exps.len,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Audio.Cnds.OnEnded,
		C3.Plugins.System.Acts.Signal,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.CreateObject,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Exps.time,
		C3.Plugins.Sprite.Cnds.PickChildren,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Cnds.PickDistance,
		C3.Plugins.Browser.Acts.ConsoleLog,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Particles.Acts.SetRate,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Sprite.Cnds.HasTags,
		C3.Plugins.System.Acts.SetFunctionReturnValue,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Exps.mid,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Acts.RemoveFromParent,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Sprite.Acts.SetDefaultColor,
		C3.Behaviors.Sin.Acts.SetPeriod,
		C3.Behaviors.Sin.Acts.SetPhase,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.System.Cnds.EvaluateExpression,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Exps.viewportmidx,
		C3.Plugins.System.Exps.viewportmidy,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.gamepad.Cnds.IsButtonDown,
		C3.Plugins.gamepad.Cnds.CompareAxis,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.gamepad.Cnds.IsButtonIndexDown,
		C3.Plugins.PlatformInfo.Cnds.IsOnWindows,
		C3.Plugins.PlatformInfo.Cnds.IsOnMacOS,
		C3.Plugins.PlatformInfo.Cnds.IsOnLinux,
		C3.Plugins.System.Cnds.OnSignal,
		C3.Plugins.System.Acts.WaitForSignal,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Acts.StopAnim,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.JavaScriptInEvents.Rappers_Event10_Act1,
		C3.Plugins.System.Exps.max,
		C3.Plugins.System.Exps.min,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.Particles.Acts.SetX,
		C3.Plugins.Sprite.Exps.BBoxRight,
		C3.Plugins.Particles.Acts.SetY,
		C3.Plugins.Particles.Cnds.OnCreated,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.System.Exps.timescale,
		C3.Plugins.Spritefont2.Exps.Count,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.System.Exps.tickcount,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.Audio.Acts.SetPaused,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.Sprite.Exps.AnimationName,
		C3.Plugins.Sprite.Acts.SetEffectEnabled
	];
};
self.C3_JsPropNameTable = [
	{Sine: 0},
	{Flash: 0},
	{MenuSelectOption: 0},
	{Browser: 0},
	{Audio: 0},
	{Gamepad: 0},
	{Keyboard: 0},
	{Sprite6: 0},
	{Sine2: 0},
	{Tween: 0},
	{MenuSelectCursor: 0},
	{GameCompanyLogo: 0},
	{Anchor: 0},
	{Transition: 0},
	{PlatformInfo: 0},
	{Credits: 0},
	{PerfectTime: 0},
	{NoteType: 0},
	{Note: 0},
	{UseMe: 0},
	{NoteTargetPos: 0},
	{SineVertical: 0},
	{SineAngle: 0},
	{Rapper: 0},
	{Sprite2: 0},
	{NoteStartPos: 0},
	{NoteTargetPos2: 0},
	{BattleBackground: 0},
	{ScoreBar: 0},
	{Bubble: 0},
	{BubbleIcon: 0},
	{Particles: 0},
	{Sprite3: 0},
	{Particles2: 0},
	{RapperSelection: 0},
	{Sprite5: 0},
	{Sprite7: 0},
	{RapperSelectArrow: 0},
	{TiledBackground2: 0},
	{Sprite9: 0},
	{Sprite13: 0},
	{PauseBackdrop: 0},
	{Sprite: 0},
	{DiffSelect: 0},
	{ScreenEffects: 0},
	{Targets: 0},
	{DelayBeforeSequenceStart: 0},
	{SequenceData: 0},
	{MusicFileName: 0},
	{BPM: 0},
	{TweenDuration: 0},
	{CreationDelay: 0},
	{TimeDiff: 0},
	{Points: 0},
	{Type: 0},
	{Index: 0},
	{RoundIndex: 0},
	{Player1FinalScore: 0},
	{Player2FinalScore2: 0},
	{MenuSelectIndex: 0},
	{IsTransitionning: 0},
	{Layout: 0},
	{Button: 0},
	{GamepadIndex: 0},
	{CurrentRoundIndex: 0},
	{CurrentPlayerIndex: 0},
	{CurrentRoundSequenceData: 0},
	{NbRound: 0},
	{Player1RapperIndex: 0},
	{Player2RapperIndex: 0},
	{Player1RoundPoints: 0},
	{Player2RoundPoints: 0},
	{Player1Points: 0},
	{Player2Points: 0},
	{RapperIndex: 0},
	{P1OK: 0},
	{P2OK: 0},
	{CurrentPlayerIndexChoosingCharacter: 0},
	{PlayerIndex: 0},
	{Next: 0},
	{ArcadeMode: 0},
	{RapperCount: 0},
	{DiffSelectIndex: 0}
];

self.InstanceType = {
	MenuSelectOption: class extends self.ISpriteFontInstance {},
	Browser: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	Gamepad: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	MenuSelectCursor: class extends self.ISpriteInstance {},
	GameCompanyLogo: class extends self.ISpriteInstance {},
	Transition: class extends self.ISpriteInstance {},
	PlatformInfo: class extends self.IInstance {},
	Credits: class extends self.ISpriteFontInstance {},
	Note: class extends self.ISpriteInstance {},
	NoteTargetPos: class extends self.ISpriteInstance {},
	Rapper: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	NoteStartPos: class extends self.ISpriteInstance {},
	NoteTargetPos2: class extends self.ISpriteInstance {},
	BattleBackground: class extends self.ISpriteInstance {},
	ScoreBar: class extends self.ISpriteInstance {},
	Bubble: class extends self.ISpriteInstance {},
	BubbleIcon: class extends self.ISpriteInstance {},
	Particles: class extends self.IParticlesInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Particles2: class extends self.IParticlesInstance {},
	RapperSelection: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	RapperSelectArrow: class extends self.ISpriteInstance {},
	TiledBackground2: class extends self.ITiledBackgroundInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	PauseBackdrop: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	DiffSelect: class extends self.ISpriteInstance {},
	ScreenEffects: class extends self.ISpriteInstance {},
	Targets: class extends self.ISpriteInstance {}
}